name: 🚀 release and deploy
on:
  workflow_dispatch:    # for debugging
  push:
    tags:
    - 'axon-dynamodb-*' # tagged by maven-release-plugin

jobs:
  build:
    name: maven build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup jdk and maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'maven'
          server-id: 'sonatype-nexus'
          server-username: ${{ secrets.DEPLOY_USERNAME }}
          server-password: ${{ secrets.DEPLOY_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: prepare release
        run: mvn -B release:prepare -P release

      - name: Publish to Apache Maven Central
        run: mvn -B release:perform -P release
