name: 🥳 merge release to main

on:
  workflow_dispatch:
  push:
    tags:
    - 'axon-dynamodb-*'

permissions:
  contents: write

jobs:
  build:
    name: merge tag to main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_TOKEN }}
          fetch-depth: 0
          fetch-tags: true
      - name: merge ${{ github.ref_name }} to main
        env:
          RELEASE_VERSION: ${{ github.ref_name }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
          git fetch --all
          git checkout -t origin/main
          git merge ${RELEASE_VERSION}
          git push
