name: ⬆️ renovate dependencies
on:
  workflow_dispatch

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.1.1
        with:
          renovate-version: 36.107.1
          token: ${{ secrets.GITHUB_TOKEN }}
